Repository element-hq/element-ios, pull requests merged in 2022-11, with the labels that each got.

#7007 Rich Text Composer: Fixing missing keystrokes + fixing long press backspace not deleting all the text
  Riot.xcworkspace/xcshareddata/swiftpm/Package.resolved
  RiotSwiftUI/Modules/Room/Composer/Test/UI/ComposerUITests.swift
  RiotSwiftUI/Modules/Room/Composer/View/Composer.swift
  changelog.d/7005.bugfix
  changelog.d/7006.bugfix
  project.yml
Labels: Trigger-PR-Build, A-Rich-Text-Editor

#7027 Labs: Rich text-editor fix for "does not support inserting custom iOS emojis"
  Riot/Modules/Room/Views/WYSIWYGInputToolbar/WysiwygInputToolbarView.swift
  RiotSwiftUI/Modules/Room/Composer/MockComposerScreenState.swift
  RiotSwiftUI/Modules/Room/Composer/Model/ComposerViewState.swift
  RiotSwiftUI/Modules/Room/Composer/Test/Unit/ComposerViewModelTests.swift
  RiotSwiftUI/Modules/Room/Composer/View/Composer.swift
  RiotSwiftUI/Modules/Room/Composer/ViewModel/ComposerViewModel.swift
  RiotSwiftUI/Modules/Room/Composer/ViewModel/ComposerViewModelProtocol.swift
  changelog.d/6946.bugfix
Labels: A-Rich-Text-Editor

#7048 Alpha build tests
  .github/workflows/release-alpha.yml
  Gemfile.lock
  fastlane/Fastfile
Labels: Trigger-PR-Build

#6993 Fixed IRC-style message and commands support in Rich text editor
  Riot/Modules/Room/RoomViewController.swift
  changelog.d/6962.bugfix
Labels: Trigger-PR-Build

#7059 Rich Text Editor: Fullscreen mode
  Riot/Modules/MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarView.h
  Riot/Modules/Room/MXKRoomViewController.h
  Riot/Modules/Room/RoomViewController.h
  Riot/Modules/Room/RoomViewController.m
  Riot/Modules/Room/RoomViewController.swift
  Riot/Modules/Room/RoomViewController.xib
  Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.h
  Riot/Modules/Room/Views/WYSIWYGInputToolbar/WysiwygInputToolbarView.swift
  RiotSwiftUI/Modules/Room/Composer/View/Composer.swift
  RiotSwiftUI/Modules/Room/Composer/ViewModel/ComposerViewModel.swift
  RiotSwiftUI/Modules/Room/Composer/ViewModel/ComposerViewModelProtocol.swift
  changelog.d/7058.change
Labels: Trigger-PR-Build

#7093 Update Rich text editor library version
  Riot.xcworkspace/xcshareddata/swiftpm/Package.resolved
  changelog.d/6930.bugfix
  changelog.d/6983.bugfix
  changelog.d/7042.bugfix
  changelog.d/7086.bugfix
  project.yml
Labels: Trigger-PR-Build
