Repository element-hq/element-ios, pull requests merged in 2023-02, with the labels that each got.

#7317 Labs: Rich text editor: enable list items indentation
  Podfile
  Riot.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Riot/Assets/en.lproj/Vector.strings
  Riot/Generated/Strings.swift
  Riot/Modules/MatrixKit/Utils/EventFormatter/HTMLFormatter.swift
  Riot/Modules/Room/Views/WYSIWYGInputToolbar/WysiwygInputToolbarView.swift
  Riot/Utils/EventFormatter+DTCoreTextFix.h
  Riot/Utils/EventFormatter+DTCoreTextFix.m
  Riot/Utils/EventFormatter.m
  Riot/target.yml
  RiotNSE/target.yml
  RiotShareExtension/target.yml
  RiotSwiftUI/Modules/Room/Composer/Model/ComposerModels.swift
  SiriIntents/target.yml
  changelog.d/7316.change
  fastlane/Fastfile
  project.yml
Labels: Trigger-PR-Build

#7342 Hide the presence info if the presence status is unknown
  Riot/Utils/Tools.m
  changelog.d/6597.change
Labels: T-Enhancement

#7351 Fix an issue where a voice message disappears after being sent
  Riot/Modules/Room/VoiceMessages/VoiceMessageController.swift
  changelog.d/7326.bugfix
Labels: T-Defect, A-Voice-Messages

#7360 Release 1.10.2
  .github/workflows/release-alpha.yml
  CHANGES.md
  Config/AppVersion.xcconfig
  Riot/Categories/MXBugReportRestClient+Riot.swift
  Riot/Modules/Common/Recents/Views/RecentTableViewCell.m
  Riot/Modules/Home/AllChats/AllChatsViewController.swift
  Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitCoordinator.swift
  Riot/Modules/KeyVerification/Device/SelfVerifyWait/KeyVerificationSelfVerifyWaitViewModel.swift
  Riot/Modules/MatrixKit/Models/Room/MXKRoomDataSource.m
  Riot/Modules/MatrixKit/Models/RoomList/MXKRecentCellData.m
  Riot/Modules/MatrixKit/Models/RoomList/MXKRecentCellDataStoring.h
  RiotSwiftUI/Modules/Room/NotificationSettings/Service/MatrixSDK/MXRoomNotificationSettingsService.swift
Labels: Trigger-PR-Build
